# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fa7e663908338c7c84a881333ff503c2fcf124192d51020bca768443b8bf6c551eee6640b74ce1b93a466c7fc4efa34a221239c30fcd3bbb59228b005ffdd1c6

test:
  secret_key_base: 010c0b0a57c0928c5821f25ba69f24dcd77a02c521b88c848402d08020ef22dd63fded3e9721a5ec198edacc080c8e08ab0e98d5a586a91d356f563b642e6bb9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
