# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 13c1202171a77a2b86d77811887078b9e705ab01635a3ebc76a780c2bc849a9dc78ef585ec13bec250addd3530cd276e9aead55b194171429737602761ae1a79

test:
  secret_key_base: 6b9607b1f47a8aeae598373f8d2ff7efd05c3d23d671c3c5cf2f3df96500477eccf42b1ac953d2101926aa98bf527f8498f960c27756cce1f7b2b0513155cd35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
